### ISSUE TITLE
Add ROS (Robot Operating System) related icons

### ISSUE THREAD

**Issue by BrunoB81HK** [BeardedBear/bearded-icons#185]
Hi!

First of all, this icon pack is great. Thank you for it!

I was wondering if it was possible to include/add ROS related file icons? It would include the following patterns:

```yaml
interfaces:
  - *.action
  - *.msg
  - *.srv
  - **/action/*.action # if *.action is not specific enough
  - **/msg/*.msg # if *.msg is not specific enough
  - **/srv/*.srv # if *.srv is not specific enough
meta-data: # This may not be specific to ROS
  - package.xml
  - plugin_description.xml
launch:
  - *.launch.py
  - **/launch/*.launch.py # if *.launch.py is not specific enough
vcstool: # https://github.com/dirk-thomas/vcstool
  - *.repos
urdf:
  - *.urdf.xacro # Maybe it should use xacro
  - *.urdf
xacro: # https://github.com/ros/xacro/tree/ros2
  - *.xacro
```

I think I have listed all of them, but I could have missed some.

The only thing that I'm not sure about are what logo/images to use as icons. Some of those tools do not have logos. I think that a good place to get inspiration is the [ROS Artwork repository](https://github.com/ros-infrastructure/artwork).
