### ISSUE TITLE
Add pre-commit related icons

### ISSUE THREAD

**Issue by BrunoB81HK** [BeardedBear/bearded-icons#186]
Hi!

Another set of icons that could be included/added are [pre-commit](https://[pre-commit](https://pre-commit.com/).com/) related file icons. It would include the following patterns:

```yaml
configs:
  - .pre-commit-config.yaml
hooks:
  - .pre-commit-hooks.yaml
```

The logo is pretty straight forward and it should not be too difficult to add variations to it.

Thanks a lot!
